<a href="https://colab.research.google.com/github/shaambhavisrivastava30-cpu/Summer-Training-3rd-Year-Harshit-Raj-Ravi-Srivastava/blob/main/Election_sentiment_analysis_India.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from textblob import TextBlob
import plotly.graph_objects as go
import plotly.express as xp

In [ ]:
modi = pd.read_csv("/content/modi_reviews.csv")
rahul = pd.read_csv("/content/rahul_reviews.csv")

In [ ]:
modi.head()

,Unnamed: 0,User,Tweet
0,0,advosushildixit,@anjanaomkashyap I am seeing you as future #bj...
1,1,jiaeur,#LokSabhaElections2019 \n23rd May 2019 will re...
2,2,PVenkatGandhi,#LokSabhaElections2019 \n23rd May 2019 will re...
3,3,TheNirbhay1,PM Modi creates a new record of being the only...
4,4,ShakeChilli,@abhijitmajumder Appointment of Successor! \n\...

In [ ]:
modi.shape

(25688, 3)

In [ ]:
rahul.head()

,Unnamed: 0,User,Tweet
0,0,Sunnysweet16,Wonder why no academic or journalist asks INC ...
1,1,drnitinchaube,Congrats for the change #australiavotes2019 an...
2,2,mrvivek07,Peopel Say “Govt Ne 70 Years Kya kiya”.\nUnse ...
3,3,JosephPravinP,"@ajaymaken @RahulGandhi And as a final touch, ..."
4,4,VandanaMegastar,#LokSabhaElections2019 Anyone not having mass ...

In [ ]:
rahul.shape

(14261, 3)

In [ ]:
TextBlob(modi["Tweet"][10]).sentiment

Sentiment(polarity=0.0, subjectivity=0.0)

In [ ]:
TextBlob(rahul["Tweet"][2]).sentiment

Sentiment(polarity=0.0, subjectivity=0.0)

In [ ]:
modi['Tweet'] = modi['Tweet'].astype(str)
rahul['Tweet'] = modi['Tweet'].astype(str)
def find_polarity(review):
    return TextBlob(review).sentiment.polarity

In [ ]:
modi['Polarity'] = modi['Tweet'].apply(find_polarity)
rahul['Polarity'] = rahul['Tweet'].apply(find_polarity)

In [ ]:
modi

,Unnamed: 0,User,Tweet,Polarity
0,0,advosushildixit,@anjanaomkashyap I am seeing you as future #bj...,0.350000
1,1,jiaeur,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000
2,2,PVenkatGandhi,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000
3,3,TheNirbhay1,PM Modi creates a new record of being the only...,0.312121
4,4,ShakeChilli,@abhijitmajumder Appointment of Successor! \n\...,0.098788
...,...,...,...,...
25683,25683,shv_indian,#1DDrive #ModiSpeaksToNews18 #LokSabhaElection...,0.000000
25684,25684,SONUPINKOO,I am seriously worried about future of Indian ...,0.209524
25685,25685,SONUPINKOO,If @narendramodi is so Bad then Why does @INCI...,-0.700000
25686,25686,SONUPINKOO,"On this 23rd March (Pakistan Day), I Urge all ...",0.000000
25687,25687,parthajit0101,"@timesofindia #ArvindKejriwal, #AAP sirji pls ...",-0.213542

In [ ]:
rahul

,Unnamed: 0,User,Tweet,Polarity
0,0,Sunnysweet16,@anjanaomkashyap I am seeing you as future #bj...,0.350000
1,1,drnitinchaube,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000
2,2,mrvivek07,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000
3,3,JosephPravinP,PM Modi creates a new record of being the only...,0.312121
4,4,VandanaMegastar,@abhijitmajumder Appointment of Successor! \n\...,0.098788
...,...,...,...,...
14256,14256,SunjayJK,@thewire_in @narendramodi It's a #BJP False Pr...,-0.400000
14257,14257,SunjayJK,#Mahagathbandhan This shows how much fear the...,0.300000
14258,14258,RAMANKAIRA,@BJP4UP @narendramodi Teacher: Give a to the p...,0.000000
14259,14259,RAMANKAIRA,I pledge to vote and support nation builder- N...,0.000000
14260,14260,RAMANKAIRA,#bjp #RahulGandhi Who is this Sambit Patra ......,0.000000

In [ ]:
modi['Label'] = np.where(modi['Polarity'] >= 0, 'Positive', 'Negative')
modi['Label'][modi['Polarity']==0] = 'Neutral'

rahul['Label'] = np.where(rahul['Polarity'] >= 0, 'Positive', 'Negative')
rahul['Label'][rahul['Polarity']==0] = 'Neutral'

/tmp/ipykernel_538/3617758754.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  modi['Label'][modi['Polarity']==0] = 'Neutral'
/tmp/ipykernel_538/3617758754.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  modi['Label'][modi['Polarity']==0] = 'Neutral'
/tmp/ipykernel_538/3617758754.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  rahul['Label'][rahul['Polarity']==0] = 'Neutral'
/tmp/ipykernel_538/3617758754.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rahul['Label'][rahul['Polarity']==0] = 'Neutral'

In [19]:
modi

,Unnamed: 0,User,Tweet,Polarity,Label
0,0,advosushildixit,@anjanaomkashyap I am seeing you as future #bj...,0.350000,Positive
1,1,jiaeur,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000,Positive
2,2,PVenkatGandhi,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000,Positive
3,3,TheNirbhay1,PM Modi creates a new record of being the only...,0.312121,Positive
4,4,ShakeChilli,@abhijitmajumder Appointment of Successor! \n\...,0.098788,Positive
...,...,...,...,...,...
25683,25683,shv_indian,#1DDrive #ModiSpeaksToNews18 #LokSabhaElection...,0.000000,Neutral
25684,25684,SONUPINKOO,I am seriously worried about future of Indian ...,0.209524,Positive
25685,25685,SONUPINKOO,If @narendramodi is so Bad then Why does @INCI...,-0.700000,Negative
25686,25686,SONUPINKOO,"On this 23rd March (Pakistan Day), I Urge all ...",0.000000,Neutral
25687,25687,parthajit0101,"@timesofindia #ArvindKejriwal, #AAP sirji pls ...",-0.213542,Negative

In [20]:
rahul

,Unnamed: 0,User,Tweet,Polarity,Label
0,0,Sunnysweet16,@anjanaomkashyap I am seeing you as future #bj...,0.350000,Positive
1,1,drnitinchaube,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000,Positive
2,2,mrvivek07,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000,Positive
3,3,JosephPravinP,PM Modi creates a new record of being the only...,0.312121,Positive
4,4,VandanaMegastar,@abhijitmajumder Appointment of Successor! \n\...,0.098788,Positive
...,...,...,...,...,...
14256,14256,SunjayJK,@thewire_in @narendramodi It's a #BJP False Pr...,-0.400000,Negative
14257,14257,SunjayJK,#Mahagathbandhan This shows how much fear the...,0.300000,Positive
14258,14258,RAMANKAIRA,@BJP4UP @narendramodi Teacher: Give a to the p...,0.000000,Neutral
14259,14259,RAMANKAIRA,I pledge to vote and support nation builder- N...,0.000000,Neutral
14260,14260,RAMANKAIRA,#bjp #RahulGandhi Who is this Sambit Patra ......,0.000000,Neutral

In [22]:
neutral_modi = modi[modi['Polarity']==0.000]
remove_neutral_modi = modi['Polarity'] . isin(neutral_modi['Polarity'])
modi.drop(modi[remove_neutral_modi].index , inplace = True)

In [23]:
print(neutral_modi.shape)
print(modi.shape)

(8206, 5)
(17482, 5)

In [24]:
neutral_rahul = rahul[rahul['Polarity']==0.000]
remove_neutral_rahul = rahul['Polarity'] . isin(neutral_modi['Polarity'])
rahul.drop(rahul[remove_neutral_rahul].index , inplace = True)

In [25]:
print(neutral_rahul.shape)
print(rahul.shape)

(4452, 5)
(9809, 5)

In [26]:
#making row count to 9000 for#modi
np.random.seed(10)
remove_n = modi.shape[0] - 9000
drop_indices = np.random.choice(modi.index, remove_n, replace=False)
df_modi = modi.drop(drop_indices)

In [27]:
print(df_modi.shape)

(9000, 5)

In [28]:
#rahul
np.random.seed(10)
remove_n =367
drop_indices = np.random.choice(rahul.index, remove_n, replace=False)
df_rahul = rahul.drop(drop_indices)

In [29]:
print(df_rahul.shape)

(9442, 5)

In [30]:
modi_count = df_modi.groupby('Label').count()
modi_count

          Unnamed: 0  User  Tweet  Polarity
Label
Negative        2629  2629   2629      2629
Positive        6371  6371   6371      6371

In [31]:
neg_modi = (modi_count['Polarity'][0] /1000)*100
pos_modi = (modi_count['Polarity'][1] / 1000) *100

/tmp/ipykernel_538/2885894007.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  neg_modi = (modi_count['Polarity'][0] /1000)*100
/tmp/ipykernel_538/2885894007.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  pos_modi = (modi_count['Polarity'][1] / 1000) *100

In [32]:
rahul_count = df_rahul.groupby('Label').count()
rahul_count

          Unnamed: 0  User  Tweet  Polarity
Label
Negative        2839  2839   2839      2839
Positive        6603  6603   6603      6603

In [33]:
neg_rahul = (rahul_count['Polarity'][0] / 1000)*100
pos_rahul = (rahul_count['Polarity'][1] / 1000) *100

/tmp/ipykernel_538/3823082536.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  neg_rahul = (rahul_count['Polarity'][0] / 1000)*100
/tmp/ipykernel_538/3823082536.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  pos_rahul = (rahul_count['Polarity'][1] / 1000) *100

In [36]:
politicians = ['Modi','Rahul']
neg_list = [neg_modi,neg_rahul]
pos_list = [pos_modi,pos_rahul]
flg = go.Figure(data=[
    go.Bar(name='Negative', x=politicians, y=neg_list),
    go.Bar(name='Positive', x=politicians, y=pos_list)])
flg